resource "random_id" "auto_generated_id" {
  byte_length = 16
}

locals {
  # Collector URI for Snowplow Analytics Ltd to collect telemetry information
  # about OSS modules being used by the community.
  collector_uri  = "telemetry-g.snowplowanalytics.com"
  tracker_app_id = "terraform-oss-modules"

  cloud             = upper(var.cloud)
  auto_generated_id = random_id.auto_generated_id.hex

  oss_context_schema = "iglu:com.snowplowanalytics.oss/oss_context/jsonschema/1-0-0"
  oss_context = {
    userProvidedId     = var.user_provided_id == "" ? null : var.user_provided_id
    autoGeneratedId    = local.auto_generated_id
    instanceId         = null
    cloud              = local.cloud
    region             = var.region
    moduleName         = var.module_name
    moduleVersion      = var.module_version
    applicationName    = var.app_name
    applicationVersion = var.app_version
  }

  contexts = [
    {
      iglu_uri = local.oss_context_schema
      payload  = jsonencode(local.oss_context)
    },
  ]
}

resource "snowplow_track_self_describing_event" "telemetry" {
  create_event = {
    iglu_uri = "iglu:com.snowplowanalytics.oss/module_create/jsonschema/1-0-0"
    payload  = "{}"
  }

  update_event = {
    iglu_uri = "iglu:com.snowplowanalytics.oss/module_update/jsonschema/1-0-0"
    payload  = "{}"
  }

  delete_event = {
    iglu_uri = "iglu:com.snowplowanalytics.oss/module_delete/jsonschema/1-0-0"
    payload  = "{}"
  }

  contexts = local.contexts

  collector_uri  = local.collector_uri
  tracker_app_id = local.tracker_app_id
}

locals {
  common_vars = {
    oss_context_schema = local.oss_context_schema

    user_provided_id_raw = var.user_provided_id
    auto_generated_id    = local.auto_generated_id
    cloud                = local.cloud
    region               = var.region
    module_name          = var.module_name
    module_version       = var.module_version
    app_version          = var.app_version

    collector_uri  = local.collector_uri
    tracker_app_id = local.tracker_app_id
  }

  amazon_linux_2023_user_data = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/amazon_linux_2023.sh.tmpl", merge(local.common_vars, { app_name = var.app_name }))
  })

  amazon_linux_2023_user_data_1 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/amazon_linux_2023.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_1 }))
  })

  amazon_linux_2023_user_data_2 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/amazon_linux_2023.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_2 }))
  })

  amazon_linux_2023_user_data_3 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/amazon_linux_2023.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_3 }))
  })

  gcp_ubuntu_24_04_user_data = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/gcp_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name }))
  })

  gcp_ubuntu_24_04_user_data_1 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/gcp_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_1 }))
  })

  gcp_ubuntu_24_04_user_data_2 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/gcp_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_2 }))
  })

  gcp_ubuntu_24_04_user_data_3 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/gcp_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_3 }))
  })

  azurerm_ubuntu_24_04_user_data = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/azurerm_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name }))
  })

  azurerm_ubuntu_24_04_user_data_1 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/azurerm_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_1 }))
  })

  azurerm_ubuntu_24_04_user_data_2 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/azurerm_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_2 }))
  })

  azurerm_ubuntu_24_04_user_data_3 = templatefile("${path.module}/templates/user-data.sh.tmpl", {
    snowplow_track_vm_telemetry = templatefile("${path.module}/templates/azurerm_ubuntu_24_04.sh.tmpl", merge(local.common_vars, { app_name = var.app_name_override_3 }))
  })
}
